version: '3.8'

services:
  # Service PostgreSQL
  postgres:
    image: postgres:latest
    env_file: ./backend/.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Service MongoDB
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    command: mongod --auth
    volumes:
      - mongo_data:/data/db
      - ./backend/scripts:/docker-entrypoint-initdb.d
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
      MONGO_INITDB_USER: ${MONGO_INITDB_USER}
      MONGO_INITDB_PASSWORD: ${MONGO_INITDB_PASSWORD}

  # Service Backend (Express)
  backend-express:
    build:
      context: ./backend
      args:
        SERVER_TYPE: express
    env_file: ./backend/.env
    ports:
      - "4002:4002"
    depends_on:
      - postgres
      - mongo

  # Service Backend (NestJS)
  backend-nest:
    build:
      context: ./backend
      args:
        SERVER_TYPE: nest
    env_file: ./backend/.env
    ports:
      - "4001:4001"
    depends_on:
      - postgres
      - mongo

  
  # Service Frontend
  frontend:
    build: ./frontend
    env_file: ./frontend/.env
    ports:
      - "3000:3000"
    depends_on:
      - backend-nest
      - backend-express

volumes:
  postgres_data:   
  mongo_data:
